### PR TITLE
A magic number scheme for serialization

### PR DESCRIPTION
**Pull request by jeizenga**
@adamnovak I implemented the magic number scheme I proposed in https://github.com/vgteam/libbdsg/issues/24. Is this still something we want?

### CODE REVIEW

**Comment by adamnovak** [comment]
I don't think the `_impl` names are quite right for this, because `serialize` is going to apply the magic number and `serialize_impl` won't; the semantics are different and one is not an implementation of the other.

Maybe call it `serialize` and `write_members` or something?  But this is definitely the approach we want to take, I think.

**Comment by ekg** [comment]
Ideally, serialize writes the magic number and load checks if it's the
expected number and barfs if not.

Other than that, I'm happy with anything that just depends on the single
magic number.

**Comment by jeizenga** [comment]
@ekg That's pretty much what happens, but the implementation is in the public-scoped `serialize` method in libhandlegraph. 

@adamnovak I have no real attachment to the naming, so I can change it if you want. The idea was that the impl methods would be hidden by scope though, since they're protected in libhandlegraph.

**Comment by adamnovak** [comment]
Yeah, only the `serialize`/`deserialize` methods should be public. But
the internal method shouldn't be whatever_impl unless it's really
*just* and implementation, I think.

**Pull request merged**
