### PR TITLE
Don't make the rank of the first node -1

### PR DESCRIPTION
**Pull request by adamnovak**
In #54 we replaced a variable that used to start at 1 with one that now starts at 0, so we need to not subtract 1 from it to get a 0-based rank.

### CODE REVIEW

**Comment by adamnovak** [comment]
This grew slightly, because the graph round trip test I was trying to get working kept shaking out more bugs, but I think I have it. This should be what I need to make https://github.com/vgteam/vg/pull/2702 pass.

**Comment by jeizenga** [comment]
think you might have fixed https://github.com/vgteam/libbdsg/issues/19 ?

**Comment by jeizenga** [comment]
Hey, actually just FYI, I just checked and it turns out that ODGI is now failing tests in `test_libbdsg::test_deletable_handle_graphs` that it used to pass. Womp womp.

**Comment by jeizenga** [comment]
Not necessarily. A couple tests are commented out disabled on ODGI right now.

**Pull request merged**
