### PR TITLE
add cmake build process, ending need for libbdsg-easy

### PR DESCRIPTION
**Pull request by ekg**
:boom:

### CODE REVIEW

**Comment by ekg** [comment]
@jeizenga @adamnovak this should eliminate the need for the second "libbdsg-easy" repository. Let's rebase around this change.

**Comment by glennhickey** [comment]
Can we use this to get the real odgi into libbdsg (if it isn't already)?

**Comment by ekg** [comment]
Yeah, it could be a good idea. I'm kind of uneasy about nesting libbdsg in
odgi.

**Comment by glennhickey** [comment]
I was thinking about just using cmake to make your odji repo a submodule of
libbdsg.

**Comment by adamnovak** [comment]
@ekg It looks like this is unconditionally getting and building the specified commits of the dependencies, even if they are already available in the environment, right?

How exactly do you see this working with vg's build system? Are we going to get libhandlegraph (or any other shared dependency) for the whole vg build from the external project inside of libbdsg? Is libbdsg going to build a libhandlegraph and vg is going to build another one and we just make sure they are always the same commit? Are we just going to keep building the old way in vg but port anything that would have used libbdsg-easy over to this?

This is the same style of build we are using in the xg repo, and we never properly integrated that into vg's build. vg is still just grabbing the source file and header file and building them itself.

**Comment by jeizenga** [comment]
FWIW, whatever the best build process is, it makes a lot more sense to me to have the graph implementations consolidated in one repository (including XG and ODGI). Especially if we're planning on publishing all of them in one paper, I think they will be way more discoverable and less confusing for users if they're in one place.

**Comment by jeizenga** [comment]
@adamnovak Would it be possible to arrange things so that VG doesn't have its own dependency on libhandlegraph and instead only uses libbdsg's version?

**Comment by adamnovak** [comment]
Maybe. We'd have to figure out where cmake puts it and either point
our include paths into there or copy the headers and binaries out. It
would make working on libhandlegraph and building vg with the modified
version pretty tough, though.

**Comment by jeizenga** [comment]
Also, I'm not sure where this OpenMP cmake configuration keeps getting copied from, but this is not the version that works on Mac (I get that this is hard to check without a Mac system handy). Take a look at xg or mmmultimap for the (uglier) configuration for OpenMP that compiles on Mac: 

https://github.com/ekg/mmmultimap/blob/master/CMakeLists.txt#L14-L35

**Comment by ekg** [comment]
Ok thanks

**Pull request merged**
